- README.md
I tried following the example in README.md and ran into two small issues.
1. The `pub` command is typically accessed through `flutter` instead of directly. On fresh Flutter installs, `pub add ...` returns `bash: pub: command not found`
2. `GoogleMapsNavigationManager` doesn't exist.  I believe this is the old name before the class was renamed / reorganized to `GoogleMapsNavigator`.
> docs: fix code snippets in README.md

- example/ios/Podfile
- example/ios/Runner.xcodeproj/project.pbxproj
- ios/google_navigation_flutter.podspec
Fixes #157 
Defines the iOS dependency pod as static framework as it is done in the driver SDK.
> chore: define ios pod as static framework

- example/lib/pages/navigation.dart
- ios/Classes/GoogleMapsNavigationView.swift
Fixes DisplayOptions.showStopSigns and DisplayOptions.showsDestinationMarkers behaviour on iOS platform
> fix: showStopLights and showDestinationMarkers functionality on iOS

- .github/workflows/analyze.yaml
- CONTRIBUTING.md
- ios/Classes/Convert.swift
Fixes ci issues with swiftformat by start using already installed homebrew
> ci: fix swiftformat and upgrade it to 0.54.6

- example/integration_test/shared.dart
- example/integration_test/t03_navigation_test.dart
- example/integration_test/t06_map_test.dart
- example/integration_test/t08_marker_polygon_polyline_circle_test.dart
- example/pubspec.yaml
- Use patrol test variants instead of for loops.
- Improve network error test by always re-enabling the network after tests, even on failure.
> chore: improve patrol tests

- android/src/main/kotlin/com/google/maps/flutter/navigation/messages.g.kt
- ios/Classes/messages.g.swift
- lib/src/method_channel/messages.g.dart
- pigeons/messages.dart
Fixes issues with static analysis done with `pana`.
As pana does not follow the `exclude` files in analysis_options file, it analyses the generated pigeon output files.
Currently the package has unused NavigationViewCreationApi that is needed for pigeon to generate the needed NavigationViewCreationOptionsDto message. Pigeon won't generate any objects that are not used in API's.
NavigationViewCreationApi itself is not ment to be used, and was marked private with "_" prefix, causing `unused_element` static analysis errors with pana.
as, messages.g.dart is not exposed from the plugin to the app-facing api, it is not a big issue at the moment.
This should be revisited on next pigeon upgrade.
> chore: expose NavigationViewCreationApi to fix static analysis

- .github/workflows/test-and-build.yaml
- tool/test-ios.sh
Upgrades simulator version for iOS native unit tests
> ci: upgrade ios simulator from iPhone 14 Pro to iPhone 16 Pro

- README.md
Updates README with information how to enable desugaring on Android and known issues with information about using packages that have conflicting Google Maps SDK versions.
Issues related to desugaring documentation:
Related to #218
Issues related on conflict with other packages impelementing Google Maps SDK for Android or iOS:
Closes #189
Related to #190
Closes #148
Related to #211
Related to #129
> docs: update README.md with desugaring instructions and known issues

- .github/workflows/publish.yml
- .github/workflows/release-please.yml
Adds publish workflow to the project.
Publish new version of the package when new tag is pushed.
> ci: add publish workflow

- .github/workflows/test-and-build.yaml
- example/integration_test/shared.dart
- example/integration_test/t03_navigation_test.dart
- example/integration_test/t08_marker_polygon_polyline_circle_test.dart
Fixes color tests in integartion tests.
Latest flutter version removed Color.value getter, causing changes on test cases.
> test: fixes and improves to integration tests

- release-please-config.json
Instead of bootstrap-sha, last-release-sha should be used to help release please to detect last release
> ci: update last-release-sha for release please

- .github/workflows/release-please.yml
- CHANGELOG.md
Pin release please action to commit that uses newer version of the release-please package (16.12.0)
https://github.com/googleapis/release-please-action/blob/7987652d64b4581673a76e33ad5e98e3dd56832f/package.json#L32
That have fix for include-v-in-tag option:
https://github.com/googleapis/release-please/blob/90058f543cd82858539fdc7d1b34eabd348edbee/CHANGELOG.md?plain=1#L78
Fix tag in changelog
> chore: pin release-please-action version

- .github/workflows/release-please.yml
Updates release-please-action version to version 4.1.4
This change updates release-please npm package from 16.12.0 to 16.14.1 fixing issues with "include-v-in-tag" option (fixed in release please version 16.12.1)
> chore: update release-please-action to version 4.1.4

- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapsNavigationSessionManager.kt
- ios/google_navigation_flutter/Sources/google_navigation_flutter/messages.g.swift
Fixes exception thrown when closing the app if navigator was not initialized.
Fixes #274
Fixes #200
> fix: android unregisterListeners navigator check on app disposal

- android/build.gradle
- example/android/app/build.gradle
Updates Navigation SDK for Android version from 6.0.2 to 6.1.0
> chore: updates Navigation SDK for Android to 6.1.0

- .github/workflows/release-please.yml
- release-please-config.json
Removes release-type from release-please-action config to allow release please to use manifest config file.
> ci: remove release-type from release-please-action config

- CONTRIBUTING.md
Removes mention about `AUTHORS` file from `CONTRIBUTION.md` that was removed earlier at https://github.com/googlemaps/flutter-navigation-sdk/pull/127
Fixes #153
> chore: remove instructions to add contribution to authors file

- example/integration_test/shared.dart
- example/integration_test/t05_camera_test.dart
- example/lib/pages/camera.dart
- lib/src/google_maps_map_view.dart
- lib/src/google_maps_navigation_view.dart
Fixes onCameraMove, onCameraIdle, onCameraMoveStarted methods on GoogleMapsMapView widget.
Fixes #287 
> fix: onCameraMove, onCameraIdle, onCameraMoveStarted methods on GoogleMapsMapView widget

- CHANGELOG.md
Adds missing changlog header to CHANGELOG.md file.
Lack of this header most likely caused visible issues with release-please automatic CHANGELOG.md modification
> chore: add changelog header to changelog

- pubspec.yaml
Release [0.5.0](https://github.com/googlemaps/flutter-navigation-sdk/releases/tag/0.5.0) introduced bug as it implemented new Color API introduced in Flutter 3.27 without updating minimun supported SDK version to Flutter 3.27.
This PR patches this.
Fixes https://github.com/googlemaps/flutter-navigation-sdk/issues/296
> fix: update minimum supported SDK version to Flutter 3.27/Dart 3.6.

- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapsNavigationView.kt
- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapsViewMessageHandler.kt
- android/src/main/kotlin/com/google/maps/flutter/navigation/messages.g.kt
- example/integration_test/shared.dart
- example/integration_test/t04_navigation_ui_test.dart
- example/integration_test/t06_map_test.dart
- example/lib/pages/navigation.dart
- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsNavigationView.swift
- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsNavigationViewMessageHandler.swift
- ios/google_navigation_flutter/Sources/google_navigation_flutter/messages.g.swift
- lib/src/google_maps_navigation_view_controller.dart
- lib/src/method_channel/map_view_api.dart
- lib/src/method_channel/messages.g.dart
- pigeons/messages.dart
- test/google_navigation_flutter_test.dart
- test/google_navigation_flutter_test.mocks.dart
- test/messages_test.g.dart
Add support for real-time disruption view setters and getters for navigationViewController:
- Future<bool> isReportIncidentButtonEnabled() 
- Future<void> setReportIncidentButtonEnabled(bool enabled)
- Future<bool> isTrafficPromptsEnabled()
- Future<void> setTrafficPromptsEnabled(bool enabled)
Resolves #336
Related to #302
> feat: support for real-time disruption settings

- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle.properties
- example/android/gradle/wrapper/gradle-wrapper.properties
Upgrades example apps AGP version to 8.6.1 support current kotlin version (2.1)
> chore: upgrade AGP version to 8.6.1 for example app

- .github/workflows/test-and-build.yaml
- example/integration_test/shared.dart
- example/integration_test/t01_initialization_test.dart
- example/pubspec.yaml
- melos.yaml
Latest patrol version 3.15.1 have issues that cause hanging CI. Pinning the patrol version to 3.14.1 for now.
Also remove verbose flag from integration tests. Verbose flag can separately be enabled with enabling debug logs for github actions workflow.
Related to https://github.com/googlemaps/flutter-navigation-sdk/issues/167
> test: pin patrol version to 3.14.1 to fix hanging tests

- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapsAutoViewMessageHandler.kt
- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapsBaseMapView.kt
- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapsViewMessageHandler.kt
- android/src/main/kotlin/com/google/maps/flutter/navigation/ImageRegistry.kt
- android/src/main/kotlin/com/google/maps/flutter/navigation/messages.g.kt
- example/lib/pages/navigation.dart
- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsAutoViewMessageHandler.swift
- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsNavigationView.swift
- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsNavigationViewMessageHandler.swift
- ios/google_navigation_flutter/Sources/google_navigation_flutter/messages.g.swift
- lib/src/google_maps_map_view.dart
- lib/src/google_maps_navigation_view.dart
- lib/src/google_navigation_flutter_android.dart
- lib/src/google_navigation_flutter_ios.dart
- lib/src/google_navigation_flutter_platform_interface.dart
- lib/src/method_channel/auto_view_api.dart
- lib/src/method_channel/map_view_api.dart
- lib/src/method_channel/messages.g.dart
- pigeons/messages.dart
- test/google_navigation_flutter_test.mocks.dart
- test/messages_test.g.dart
Make sure view event listeners are initialized as soon as view is created to avoid missing view events on map initialization.
Intergration tests fail time to time as some event related to map initialization never occur; reason most likely is that listeners are initialized a bit late. This PR moves event listener initialization right after platform view is created and viewId is known. View controller is returned after mapView is initialized as before.
> fix: initialize view listeners on platform view creation

- ios/google_navigation_flutter/Sources/google_navigation_flutter/BaseCarSceneDelegate.swift
Hides the Report Incident button introduced in the latest SDK version from the CarPlay view, as it cannot be interacted with.
> fix: hide report incident button from the carplay view

- lib/src/types/navigation_destinations.dart
- test/google_navigation_flutter_test.dart
- test/navigation_types_test.dart
- Add assert to not allow creating NavigationWaypoint with both target and placeID.
Fixes: #382 
> fix: add assert to NavigationWaypoint constructor

- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsNavigationSessionManager.swift
This PR fixes issue where GoogleMapsNavigator.allowBackgroundLocationUpdates function was not working on iOS. 
Fixes: https://github.com/googlemaps/flutter-navigation-sdk/issues/400
> fix: fix background location updates on iOS

- README.md
Readme update for the set destinations part regarding waiting for initial user location.
> docs: add a note about user location in the readme

- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapView.kt
- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapsAutoMapView.kt
- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapsBaseMapView.kt
- android/src/main/kotlin/com/google/maps/flutter/navigation/GoogleMapsNavigationView.kt
Adds support for state aware lifecycle handling to MapView and NavigationView for Android platform.
Fixes #452
Related to #412
Related to https://github.com/googlemaps/flutter-navigation-sdk/issues/397#issuecomment-3210473149
> fix: view dispose crash on android if view is on background

- .github/workflows/analyze.yaml
- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsAutoViewMessageHandler.swift
- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsNavigationSessionManager.swift
- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsNavigationSessionMessageHandler.swift
- ios/google_navigation_flutter/Sources/google_navigation_flutter/GoogleMapsNavigationViewMessageHandler.swift
CI uses updated swift-formatter version 602.0.0
This PR reformats codebase with thsi formatter
> chore: reformat codebase with swift-format version 602.0.0

- lib/src/types/circles.dart
- lib/src/types/images.dart
- lib/src/types/lat_lng.dart
- lib/src/types/lat_lng_bounds.dart
- lib/src/types/markers.dart
- lib/src/types/navigation_destinations.dart
- lib/src/types/navigation_view_types.dart
- lib/src/types/navinfo.dart
- lib/src/types/polygons.dart
- lib/src/types/polylines.dart
- lib/src/types/simulation.dart
- lib/src/types/stroke_patterns.dart
- lib/src/types/view_initialization_options.dart
Overrides internal objects toString methods to give better string presentation of the data
> feat: improve string presentation for internal classes
